a_clip: 0.5
a_lr: 0.001
algo: ddpg
batch_size: 256
buffer_size: 100000
c_clip: 0.5
c_lr: 0.001
episode_length: 200
epsilon: 0.5
epsilon_speed: 0.99998
game_name: snakes_3v3
gamma: 0.95
load_model: false
load_model_run: 2
load_model_run_episode: 4000
log_dir: '20210814_172011'
max_episodes: 50000
model_episode: 0
output_activation: softmax
save_interval: 1000
seed: 1
tau: 0.001
use_gumbel: true
